# Generated by Django 2.1.7 on 2019-03-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('gmail', models.CharField(max_length=50)),
                ('status', models.CharField(default='F', max_length=2)),
                ('created', models.DateField(default='2019-03-12')),
                ('due_date', models.DateField(default='2019-03-12')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='upgrad.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
